/**
 * Generic productive compound splitter. All language-specific behavior —
 * locale case rules, linking elements, inflection suffixes — arrives through
 * the LanguageCompoundSplittingConfig declared by the language package
 * (see LanguageData.compoundSplitting). This module carries no language
 * conditionals: a language splits compounds iff its package declares a config.
 */
import type { LanguageCompoundSplittingConfig } from '../../types';

export type CompoundSource = 'attested' | 'generated';

export interface CompoundLexiconEntry {
  lemma: string;
  entryId?: string;
}

export interface CompoundPart extends CompoundLexiconEntry {
  parts?: readonly CompoundPart[];
  linkingElement?: string;
  /**
   * True when this part's lemma comes from the lexicon the analysis was built
   * from; absent when the part was generated by the splitter without lexicon
   * backing (a guessed sub-word). Drives provenance reporting.
   */
  attested?: boolean;
}

/**
 * How an analysis was produced and what grounds it (REQ43 provenance).
 */
export interface CompoundProvenance {
  source: CompoundSource;
  confidence: number;
  /**
   * Lexicon entries grounding the decomposition, in leaf order — the entryId
   * when the lexicon entry carries one, else its lemma. Only attested leaves
   * contribute; guessed parts leave no basis.
   */
  lexiconBasis: readonly string[];
}
/**
 * Transient parse of a productive/unseen compound form — read-only, never
 * persisted, and never written into the linguistic graph. Attested compound
 * structure belongs to the Tier-2 graph (surface entities + component-of
 * relations, emitted by package-side Python builders); this tree mirrors that
 * vocabulary 1:1 (leaf lemmas ↔ surface labels, nesting ↔ component-of) so the
 * two representations correspond, but they are not the same store. Package
 * builders (e.g. build_de) emit attested component-of relations, and
 * graph/morphology/attested.ts consumes them; this tree covers the
 * productive/unseen remainder at runtime.
 */
export interface CompoundAnalysis {
  form: string;
  lemma: string;
  source: CompoundSource;
  confidence: number;
  provenance: CompoundProvenance;
  parts: readonly CompoundPart[];
  /** Linking element that connected the first part, when the strategy derived one. */
  linkingElement?: string;
  /**
   * True when several distinct decompositions survived dedupe for this form
   * (REQ43 honesty). `parts` is the preferred parse — the leftmost split,
   * deterministically — and the remaining parses are recorded in
   * `alternatives` instead of being silently dropped.
   */
  ambiguous: boolean;
  /** Alternative parses when `ambiguous`; empty otherwise. */
  alternatives: readonly CompoundAnalysis[];
}

export type CompoundLexicon = ReadonlyMap<string, CompoundLexiconEntry>;

/** Cross-language sanity bound on a compound leaf; config may override. */
export const MIN_PART_LENGTH = 3;

export function createCompoundLexicon(entries: readonly CompoundLexiconEntry[], locale: string): Map<string, CompoundLexiconEntry> {
  return new Map(entries.map((entry) => [entry.lemma.toLocaleLowerCase(locale), entry]));
}

/** Removes inflection candidates before, and independently from, compound splitting. */
export function stripInflection(form: string, config: LanguageCompoundSplittingConfig): string[] {
  const normalized = form.trim();
  const minPartLength = config.minPartLength ?? MIN_PART_LENGTH;
  if (normalized.length < minPartLength) return [];
  return [normalized, ...(config.inflectionSuffixes ?? [])
    .filter((suffix) => normalized.toLocaleLowerCase(config.locale).endsWith(suffix) && normalized.length - suffix.length >= minPartLength)
    .map((suffix) => normalized.slice(0, -suffix.length))];
}

export function decomposeCompound(form: string, lexicon: CompoundLexicon, config: LanguageCompoundSplittingConfig): CompoundAnalysis | null {
  const normalized = form.trim();
  const minPartLength = config.minPartLength ?? MIN_PART_LENGTH;
  if (!/^[\p{L}]+$/u.test(normalized) || normalized.length < minPartLength) return null;
  const attested = lookup(normalized, lexicon, config.locale);
  if (attested) return atomicAnalysis(normalized, attested);

  // Valid parses survive independent inflection stripping, dedupe, and the
  // shape gate (≥2 leaves, no tiny leaf). Previously a form with 2+ surviving
  // parses returned null, silently hiding real ambiguity; REQ43 records it.
  const candidates = stripInflection(normalized, config)
    .flatMap((lemma) => splitCompound(lemma, lexicon, config).map((parts) => ({ lemma, parts })));
  const seen = new Set<string>();
  const valid: CompoundAnalysis[] = [];
  for (const { lemma, parts } of candidates) {
    const leaves = leafParts(parts);
    if (leaves.length < 2 || leaves.some((part) => part.lemma.length < minPartLength)) continue;
    const key = `${lemma}:${partKey(parts)}`;
    if (seen.has(key)) continue;
    seen.add(key);
    valid.push(generatedAnalysis(normalized, lemma, parts, leaves));
  }
  if (valid.length === 0) return null;

  // Preferred parse = the leftmost split (splitCompound scans boundaries
  // ascending). Every terminal leaf is lexicon-attested by construction, so
  // no quality ordering exists beyond determinism; consumers can inspect
  // `alternatives` to weigh other parses.
  const [preferred, ...alternatives] = valid;
  return alternatives.length > 0
    ? { ...preferred, ambiguous: true, alternatives }
    : preferred;
}

function generatedAnalysis(form: string, lemma: string, parts: readonly CompoundPart[], leaves: readonly CompoundPart[]): CompoundAnalysis {
  const confidence = Math.min(0.9, 0.5 + leaves.length * 0.1 + 0.1 + 0.1);
  return {
    form,
    lemma,
    source: 'generated',
    parts,
    confidence,
    provenance: { source: 'generated', confidence, lexiconBasis: leaves.filter((leaf) => leaf.attested).map((leaf) => leaf.entryId ?? leaf.lemma) },
    linkingElement: parts[0]?.linkingElement,
    ambiguous: false,
    alternatives: [],
  };
}

function atomicAnalysis(form: string, entry: CompoundLexiconEntry): CompoundAnalysis {
  const part = { ...entry, attested: true };
  return {
    form,
    lemma: entry.lemma,
    source: 'attested',
    confidence: 1,
    provenance: { source: 'attested', confidence: 1, lexiconBasis: [entry.entryId ?? entry.lemma] },
    parts: [part],
    ambiguous: false,
    alternatives: [],
  };
}

function splitCompound(word: string, lexicon: CompoundLexicon, config: LanguageCompoundSplittingConfig): CompoundPart[][] {
  const minPartLength = config.minPartLength ?? MIN_PART_LENGTH;
  const candidates: CompoundPart[][] = [];
  for (let boundary = minPartLength; boundary <= word.length - minPartLength; boundary += 1) {
    for (const linkingElement of config.linkingElements) {
      if (word.slice(boundary, boundary + linkingElement.length).toLocaleLowerCase(config.locale) !== linkingElement) continue;
      const left = word.slice(0, boundary);
      const right = word.slice(boundary + linkingElement.length);
      if (right.length < minPartLength) continue;
      const leftEntry = lookup(left, lexicon, config.locale);
      if (!leftEntry) continue;
      const rightParts = parsePart(right, lexicon, config);
      if (!rightParts) continue;
      candidates.push([{ ...leftEntry, attested: true, linkingElement: linkingElement || undefined }, rightParts]);
    }
  }
  return candidates;
}

function parsePart(word: string, lexicon: CompoundLexicon, config: LanguageCompoundSplittingConfig): CompoundPart | null {
  const entry = lookup(word, lexicon, config.locale);
  const nested = splitCompound(word, lexicon, config);
  if (nested.length > 1) return null;
  if (nested.length === 1) {
    const parts = nested[0];
    return {
      ...(entry ? { ...entry, attested: true } : { lemma: word[0]!.toLocaleUpperCase(config.locale) + word.slice(1) }),
      parts,
      linkingElement: parts[0]?.linkingElement,
    };
  }
  return entry ? { ...entry, attested: true } : null;
}

/** Lexicon keys are locale-lowercased at build time; queries normalize identically. */
function lookup(word: string, lexicon: CompoundLexicon, locale: string): CompoundLexiconEntry | undefined {
  return lexicon.get(word.toLocaleLowerCase(locale));
}

function partKey(parts: readonly CompoundPart[]): string {
  return parts.map((part) => `${part.lemma}[${part.linkingElement ?? ''}:${part.parts ? partKey(part.parts) : ''}]`).join('+');
}

function leafParts(parts: readonly CompoundPart[]): CompoundPart[] {
  return parts.flatMap((part) => part.parts ? leafParts(part.parts) : [part]);
}

