export type GermanCompoundSource = 'attested' | 'generated';

export interface GermanLexiconEntry {
  lemma: string;
  entryId?: string;
  gender?: 'm' | 'f' | 'n';
}

export interface GermanCompoundPart extends GermanLexiconEntry {
  parts?: readonly GermanCompoundPart[];
  linkingElement?: string;
  /**
   * True when this part's lemma comes from the lexicon the analysis was built
   * from; absent when the part was generated by the splitter without lexicon
   * backing (a guessed sub-word). Drives provenance reporting.
   */
  attested?: boolean;
}

/**
 * How an analysis was produced and what grounds it (REQ43 provenance).
 */
export interface GermanCompoundProvenance {
  source: GermanCompoundSource;
  confidence: number;
  /**
   * Lexicon entries grounding the decomposition, in leaf order — the entryId
   * when the lexicon entry carries one, else its lemma. Only attested leaves
   * contribute; guessed parts leave no basis.
   */
  lexiconBasis: readonly string[];
}

export interface GermanCompoundAnalysis {
  form: string;
  lemma: string;
  source: GermanCompoundSource;
  confidence: number;
  provenance: GermanCompoundProvenance;
  parts: readonly GermanCompoundPart[];
  head: GermanCompoundPart;
  linkingElement?: string;
  /**
   * True when several distinct decompositions survived dedupe for this form
   * (REQ43 honesty). `parts` is the preferred parse — the leftmost split,
   * deterministically — and the remaining parses are recorded in
   * `alternatives` instead of being silently dropped.
   */
  ambiguous: boolean;
  /** Alternative parses when `ambiguous`; empty otherwise. */
  alternatives: readonly GermanCompoundAnalysis[];
}

export type GermanCompoundLexicon = ReadonlyMap<string, GermanLexiconEntry>;

const LINKING_ELEMENTS = ['', 'es', 'en', 'er', 'n', 's'] as const;
const INFLECTION_SUFFIXES = ['ern', 'en', 'er', 'es', 'e', 'n', 's'] as const;
const MIN_PART_LENGTH = 3;

export function createGermanCompoundLexicon(entries: readonly GermanLexiconEntry[]): Map<string, GermanLexiconEntry> {
  return new Map(entries.map((entry) => [entry.lemma.toLocaleLowerCase('de'), entry]));
}

/** Removes inflection candidates before, and independently from, compound splitting. */
export function stripGermanInflection(form: string): string[] {
  const normalized = form.trim();
  if (normalized.length < MIN_PART_LENGTH) return [];
  return [normalized, ...INFLECTION_SUFFIXES
    .filter((suffix) => normalized.toLocaleLowerCase('de').endsWith(suffix) && normalized.length - suffix.length >= MIN_PART_LENGTH)
    .map((suffix) => normalized.slice(0, -suffix.length))];
}

export function decomposeGermanCompound(form: string, lexicon: GermanCompoundLexicon): GermanCompoundAnalysis | null {
  const normalized = form.trim();
  if (!/^[\p{L}]+$/u.test(normalized) || normalized.length < MIN_PART_LENGTH) return null;
  const attested = lookup(normalized, lexicon);
  if (attested) return atomicAnalysis(normalized, attested);

  // Valid parses survive independent inflection stripping, dedupe, and the
  // shape gate (≥2 leaves, no tiny leaf). Previously a form with 2+ surviving
  // parses returned null, silently hiding real ambiguity; REQ43 records it.
  const candidates = stripGermanInflection(normalized)
    .flatMap((lemma) => splitCompound(lemma, lexicon).map((parts) => ({ lemma, parts })));
  const seen = new Set<string>();
  const valid: GermanCompoundAnalysis[] = [];
  for (const { lemma, parts } of candidates) {
    const leaves = leafParts(parts);
    if (leaves.length < 2 || leaves.some((part) => part.lemma.length < MIN_PART_LENGTH)) continue;
    const key = `${lemma}:${partKey(parts)}`;
    if (seen.has(key)) continue;
    seen.add(key);
    valid.push(generatedAnalysis(normalized, lemma, parts, leaves));
  }
  if (valid.length === 0) return null;

  // Preferred parse = the leftmost split (splitCompound scans boundaries
  // ascending). Every terminal leaf is lexicon-attested by construction, so
  // no quality ordering exists beyond determinism; consumers can inspect
  // `alternatives` to weigh other parses.
  const [preferred, ...alternatives] = valid;
  return alternatives.length > 0
    ? { ...preferred, ambiguous: true, alternatives }
    : preferred;
}

function generatedAnalysis(form: string, lemma: string, parts: GermanCompoundPart[], leaves: GermanCompoundPart[]): GermanCompoundAnalysis {
  const head = rightmost(parts);
  const confidence = Math.min(0.9, 0.5 + leaves.length * 0.1 + 0.1 + 0.1);
  return {
    form,
    lemma,
    source: 'generated',
    confidence,
    provenance: { source: 'generated', confidence, lexiconBasis: leaves.filter((leaf) => leaf.attested).map((leaf) => leaf.entryId ?? leaf.lemma) },
    parts,
    head,
    linkingElement: parts[0]?.linkingElement,
    ambiguous: false,
    alternatives: [],
  };
}

function atomicAnalysis(form: string, entry: GermanLexiconEntry): GermanCompoundAnalysis {
  const part = { ...entry, attested: true };
  return {
    form,
    lemma: entry.lemma,
    source: 'attested',
    confidence: 1,
    provenance: { source: 'attested', confidence: 1, lexiconBasis: [entry.entryId ?? entry.lemma] },
    parts: [part],
    head: part,
    ambiguous: false,
    alternatives: [],
  };
}

function splitCompound(word: string, lexicon: GermanCompoundLexicon): GermanCompoundPart[][] {
  const candidates: GermanCompoundPart[][] = [];
  for (let boundary = MIN_PART_LENGTH; boundary <= word.length - MIN_PART_LENGTH; boundary += 1) {
    for (const linkingElement of LINKING_ELEMENTS) {
      if (word.slice(boundary, boundary + linkingElement.length).toLocaleLowerCase('de') !== linkingElement) continue;
      const left = word.slice(0, boundary);
      const right = word.slice(boundary + linkingElement.length);
      if (right.length < MIN_PART_LENGTH) continue;
      const leftEntry = lookup(left, lexicon);
      if (!leftEntry) continue;
      const rightParts = parsePart(right, lexicon);
      if (!rightParts) continue;
      candidates.push([{ ...leftEntry, attested: true, linkingElement: linkingElement || undefined }, rightParts]);
    }
  }
  return candidates;
}

function parsePart(word: string, lexicon: GermanCompoundLexicon): GermanCompoundPart | null {
  const entry = lookup(word, lexicon);
  const nested = splitCompound(word, lexicon);
  if (nested.length > 1) return null;
  if (nested.length === 1) {
    const parts = nested[0];
    return {
      ...(entry ? { ...entry, attested: true } : { lemma: word[0]!.toLocaleUpperCase('de') + word.slice(1) }),
      parts,
      linkingElement: parts[0]?.linkingElement,
    };
  }
  return entry ? { ...entry, attested: true } : null;
}

function lookup(word: string, lexicon: GermanCompoundLexicon): GermanLexiconEntry | undefined {
  return lexicon.get(word.toLocaleLowerCase('de'));
}

function partKey(parts: readonly GermanCompoundPart[]): string {
  return parts.map((part) => `${part.lemma}[${part.linkingElement ?? ''}:${part.parts ? partKey(part.parts) : ''}]`).join('+');
}

function leafParts(parts: readonly GermanCompoundPart[]): GermanCompoundPart[] {
  return parts.flatMap((part) => part.parts ? leafParts(part.parts) : [part]);
}

function rightmost(parts: readonly GermanCompoundPart[]): GermanCompoundPart {
  const part = parts[parts.length - 1]!;
  return part.parts ? rightmost(part.parts) : part;
}
