import { useState } from 'react';
import { ApiClient } from '../api/client';
import type { CsvPreview } from '../api/types';
const api = new ApiClient();
export function CsvImportDialog({ groupId, onImported }: { groupId: string; onImported(): void }) {
  const [open,setOpen]=useState(false); const [csv,setCsv]=useState('email,display_name,identity_type,group_slug\n'); const [preview,setPreview]=useState<CsvPreview|null>(null); const [error,setError]=useState<string|null>(null);
  const runPreview=async()=>{try{setPreview(await api.get<CsvPreview>(`/api/groups/${encodeURIComponent(groupId)}/provisioning/csv/preview`,{method:'POST',body:JSON.stringify({csv})}));setError(null);}catch(caught){setError(caught instanceof Error?caught.message:'CSV preview failed')}};
  const runImport=async()=>{try{await api.get(`/api/groups/${encodeURIComponent(groupId)}/provisioning/csv/import`,{method:'POST',body:JSON.stringify({csv,idempotencyKey:crypto.randomUUID()})});setOpen(false);onImported();}catch(caught){setError(caught instanceof Error?caught.message:'CSV import failed')}};
  return <>{<button className="secondary-action" onClick={()=>setOpen(true)}>Import CSV</button>}{open&&<div className="dialog-backdrop" role="presentation"><section role="dialog" aria-modal="true" aria-labelledby="csv-title" className="console-dialog"><h2 id="csv-title">Import users from CSV</h2><p>Preview validates every row before any account is changed.</p><textarea aria-label="CSV data" value={csv} onChange={(event)=>{setCsv(event.currentTarget.value);setPreview(null)}} />{error&&<p role="alert">{error}</p>}{preview&&<div aria-label="CSV preview"><strong>{preview.validRows} valid rows</strong>{preview.errors.map((item)=><p key={`${item.row}-${item.message}`}>Row {item.row}: {item.message}</p>)}</div>}<footer><button onClick={()=>setOpen(false)}>Cancel</button><button onClick={()=>void runPreview()}>Preview</button><button disabled={preview===null||preview.errors.length>0} onClick={()=>void runImport()}>Import</button></footer></section></div>}</>;
}
