/**
 * Normalization-semantics versioning for persisted, key-derived data.
 *
 * v1 (legacy): casing steps used AMBIENT `toLocaleLowerCase()` — the same word
 * could hash differently on machines with different host locales (e.g. Turkish
 * `I` → `ı`). Such legacy keys are NOT deterministically reconstructible.
 * v2 (current): casing steps are pinned to the root locale (`'und'`) — fully
 * deterministic across machines.
 *
 * Migration policy (see design doc §2):
 * - source-backed records (raw word available) are rebuilt under v2 keys;
 * - key-only records (wordSyncSeen, knownUntracked, event buckets without a raw
 *   surface) keep their legacy keys, preserved read-only;
 * - `legacyCasingCandidates` provides best-effort continuity probing of legacy
 *   keys when the raw surface IS available — an optimization, never a guarantee.
 */
export const CURRENT_NORMALIZATION_VERSION = 2;

/** Locales whose simple lowercasing can diverge from the root locale. Non-exhaustive by design; probing is an optimization. */
const LEGACY_PROBE_LOCALES = ['und', 'tr', 'az', 'lt'] as const;

/**
 * Deterministic candidates for LEGACY keys of a raw word, generated by casing
 * under each probe locale. Order-stable, deduplicated. Used only to PROBE
 * legacy namespaces for continuity — never to mint new v2 keys.
 */
export function legacyCasingCandidates(word: string): string[] {
  const seen = new Set<string>();
  for (const locale of LEGACY_PROBE_LOCALES) {
    seen.add(word.toLocaleLowerCase(locale));
  }
  return [...seen];
}

/**
 * Version stamp policy for a loaded store:
 * - absent → current (legacy stores adopt the current semantics; source-backed
 *   indexes rebuild from raw fields);
 * - legacy (< current) → current (same);
 * - future (> current) → PRESERVED, never silently downgraded — the newer
 *   build owns those semantics.
 */
export function resolveNormalizationVersion(stored?: number): number {
  if (stored === undefined) return CURRENT_NORMALIZATION_VERSION;
  return Math.max(stored, CURRENT_NORMALIZATION_VERSION);
}
