import { describe, expect, it } from 'vitest';
import { buildExplainerGeneratedByLabel, getExplainerProviderTranslationKey } from './explainerProviderLabel';

const translations: Record<string, string> = {
  'mlearn.Explainer.GeneratedBy': 'Generated by {provider}',
  'mlearn.Explainer.Provider.Builtin': 'local AI',
  'mlearn.Explainer.Provider.Ollama': 'Ollama',
  'mlearn.Explainer.Provider.Cloud': 'cloud AI',
};

const translate = (key: string, params?: Record<string, string>) => {
  const template = translations[key] ?? key;
  return template.replace('{provider}', params?.provider ?? '');
};

describe('explainerProviderLabel', () => {
  it('maps the cloud provider to the cloud explainer label key', () => {
    expect(getExplainerProviderTranslationKey('cloud')).toBe('mlearn.Explainer.Provider.Cloud');
  });

  it('builds the cloud generated-by label without falling back to local AI', () => {
    expect(buildExplainerGeneratedByLabel('cloud', translate)).toBe('Generated by cloud AI');
  });

  it('builds the builtin generated-by label using the builtin provider text', () => {
    expect(buildExplainerGeneratedByLabel('builtin', translate)).toBe('Generated by local AI');
  });

  it('builds the Ollama generated-by label using the Ollama provider text', () => {
    expect(buildExplainerGeneratedByLabel('ollama', translate)).toBe('Generated by Ollama');
  });
});